// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/namenodepb.proto

package namenodepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage int32   `protobuf:"varint,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Row   int32   `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	Moves []int32 `protobuf:"varint,3,rep,packed,name=moves,proto3" json:"moves,omitempty"`
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_namenodepb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_namenodepb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequest.ProtoReflect.Descriptor instead.
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return file_api_namenodepb_proto_rawDescGZIP(), []int{0}
}

func (x *SaveRequest) GetStage() int32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

func (x *SaveRequest) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *SaveRequest) GetMoves() []int32 {
	if x != nil {
		return x.Moves
	}
	return nil
}

type SaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_namenodepb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_namenodepb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResponse.ProtoReflect.Descriptor instead.
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return file_api_namenodepb_proto_rawDescGZIP(), []int{1}
}

func (x *SaveResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_api_namenodepb_proto protoreflect.FileDescriptor

var file_api_namenodepb_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x70, 0x62, 0x22, 0x4b, 0x0a, 0x0b, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x76,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x73, 0x22,
	0x26, 0x0a, 0x0c, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x4e, 0x0a, 0x0f, 0x4e, 0x61, 0x6d, 0x65, 0x6e,
	0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x04, 0x53, 0x61,
	0x76, 0x65, 0x12, 0x17, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e,
	0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6e, 0x61,
	0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x6e,
	0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_namenodepb_proto_rawDescOnce sync.Once
	file_api_namenodepb_proto_rawDescData = file_api_namenodepb_proto_rawDesc
)

func file_api_namenodepb_proto_rawDescGZIP() []byte {
	file_api_namenodepb_proto_rawDescOnce.Do(func() {
		file_api_namenodepb_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_namenodepb_proto_rawDescData)
	})
	return file_api_namenodepb_proto_rawDescData
}

var file_api_namenodepb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_namenodepb_proto_goTypes = []interface{}{
	(*SaveRequest)(nil),  // 0: namenodepb.SaveRequest
	(*SaveResponse)(nil), // 1: namenodepb.SaveResponse
}
var file_api_namenodepb_proto_depIdxs = []int32{
	0, // 0: namenodepb.NamenodeService.Save:input_type -> namenodepb.SaveRequest
	1, // 1: namenodepb.NamenodeService.Save:output_type -> namenodepb.SaveResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_namenodepb_proto_init() }
func file_api_namenodepb_proto_init() {
	if File_api_namenodepb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_namenodepb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_namenodepb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_namenodepb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_namenodepb_proto_goTypes,
		DependencyIndexes: file_api_namenodepb_proto_depIdxs,
		MessageInfos:      file_api_namenodepb_proto_msgTypes,
	}.Build()
	File_api_namenodepb_proto = out.File
	file_api_namenodepb_proto_rawDesc = nil
	file_api_namenodepb_proto_goTypes = nil
	file_api_namenodepb_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NamenodeServiceClient is the client API for NamenodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NamenodeServiceClient interface {
	Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error)
}

type namenodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNamenodeServiceClient(cc grpc.ClientConnInterface) NamenodeServiceClient {
	return &namenodeServiceClient{cc}
}

func (c *namenodeServiceClient) Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, "/namenodepb.NamenodeService/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NamenodeServiceServer is the server API for NamenodeService service.
type NamenodeServiceServer interface {
	Save(context.Context, *SaveRequest) (*SaveResponse, error)
}

// UnimplementedNamenodeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNamenodeServiceServer struct {
}

func (*UnimplementedNamenodeServiceServer) Save(context.Context, *SaveRequest) (*SaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}

func RegisterNamenodeServiceServer(s *grpc.Server, srv NamenodeServiceServer) {
	s.RegisterService(&_NamenodeService_serviceDesc, srv)
}

func _NamenodeService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamenodeServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenodepb.NamenodeService/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamenodeServiceServer).Save(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NamenodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "namenodepb.NamenodeService",
	HandlerType: (*NamenodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _NamenodeService_Save_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/namenodepb.proto",
}
